services:
  inventory:
    build: ./inventory_server
    ports:
      - "1337:1337"

  sd-adapter:
    image: python:3.12-slim
    depends_on: [inventory]
    working_dir: /app
    volumes:
      - ./adapter/app.py:/app/app.py:ro
    environment:
      INVENTORY_URL: http://inventory:1337/inventory
      SENSOR_PORT: "9100"
    command: ["sh","-lc","pip install --no-cache-dir flask requests && python3 /app/app.py"]
    ports:
      - "8001:8001"

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [sd-adapter]
