version: "3.9"

services:
  inventory:
    build: ./inventory_server
    ports:
      - "1337:1337"

  sd-adapter:
    image: python:3.12-slim
    depends_on: [inventory]
    command: >
      bash -lc "
      pip install --no-cache-dir flask requests &&
      python - <<'PY'
      from flask import Flask, jsonify
      import requests, os
      app = Flask(__name__)
      INVENTORY_URL = os.environ.get('INVENTORY_URL', 'http://inventory:1337/inventory')
      SENSOR_PORT   = os.environ.get('SENSOR_PORT', '9100')
      @app.get('/sd')
      def sd():
          try:
              names = requests.get(INVENTORY_URL, timeout=3).json() or []
          except Exception:
              names = []
          targets = [f'{name}:{SENSOR_PORT}' for name in names]
          return jsonify([{"targets": targets, "labels": {"job": "sensor"}}])
      app.run(host='0.0.0.0', port=8001)
      PY
      "
    environment:
      - INVENTORY_URL=http://inventory:1337/inventory
      - SENSOR_PORT=9100
    expose:
      - "8001"

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on: [sd-adapter]
